config/routes.rb
Rails.application.routes.draw do
  #mount ActionCable
  mount ActionCable.server => '/cable'

  resources :messages, only: [:new, :create]
  
  get '/rooms', to: "rooms#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "orders#index"
  resources :orders
  get "/kitchen", to: "orders#kitchen"
  get "/pickup", to: "orders#pickup"
  get "/station", to: "orders#new"

  # API routes
  namespace :api do
    namespace :v1 do
      resources :orders, only: [:create, :index]
      patch "orders/archive", to: "orders#archive_all", as: :archive_path
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  validates :first_name, length: { minimum: 1, maximum: 50 }
  validates :last_name, length: { minimum: 1, maximum: 50  }
  validates :drink, length: { minimum: 1,  maximum: 50 }
  validates :special_instructions, length: { maximum: 50 }

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::BaseController
  def index
    render json: Order.all
  end
  def create
    @order = Order.new(order_params)
    @order.status = "IN_PROGRESS"

    if @order.save
      render json: @order
    else
      render error: { error: 'Unable to process order'}, status: 400
    end
  end

  def archive_all
    MarkOrderArchivedJob.set(wait: 30.seconds).perform_later
    render json: {"message" => "orders will be marked archived"}, status: "200 OK"
  end

  private
  def order_params
    params.require(:order).permit(:first_name, :last_name, :drink, :phone_number, :special_instructions)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    print "car"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end
  def create
    @message = Message.create(msg_params)
    if @message.save
      ActionCable.server.broadcast "room_channel",
                                   content: @message.content
    else

    end
  end
  private
  def msg_params
    params.require(:message).permit(:content)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def kitchen
    @orders = Order.all
  end

  def pickup
    @orders = Order.where("status = 'COMPLETED'")
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    logger.info("order params =>" + order_params.to_s)
    @order.status = "IN_PROGRESS"

    if @order.save
      redirect_to @order
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @order = Order.find(params[:id])
    change_status
  end

  def update
    change_status
  end

  def change_status
    @order = Order.find(params[:id])
    @order.status = "COMPLETED"
    if @order.save
      ActionCable.server.broadcast "order_channel",
                                   content: @order.order_id
      redirect_to @order
    else
      redirect_to @order, notice: "Status updated to #{@order.status}"
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def order_params
    params.require(:order).permit(:first_name, :last_name, :drink, :phone_number, :special_instructions)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @message = Message.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boba Station</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_path %>">The World's Only Free Boba Shop</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= kitchen_path %>">Kitchen</a>
<!--            <a href ="<%#= kitchen_path %>">Kitchen</a>-->
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= station_path %>">Order Station</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= pickup_path %>">Pick Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= rooms_path %>" tabindex="-1" aria-disabled="true">Chat Room</a>
          </li>
        </ul>

          <%= button_to "Close Kitchen", api_v1_archive_path_url, :class => "btn btn-outline-warning", method: :patch %>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<ul>
  <li>
    <a href ="<%= kitchen_path %>">Kitchen</a>
  </li>
  <li>
    <a href ="<%= station_path %>">Order Station</a>
  </li>
</ul>

app/views/orders/kitchen.html.erb
<div class="container" >
  <div id="order-update">

  </div>
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Drink</th>
      <th scope="col">Special Instructions</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.first_name %></td>
        <td><%= order.last_name %></td>
        <td><%= order.drink %></td>
        <td><%= order.special_instructions %></td>
        <td><%= order.status %></td>
        <td>
          <%= button_to "Delete Order", order_path(order), :class => "btn btn-danger" , method: :delete%>
          <%= button_to "Mark as Completed", order_path(order), :class => "btn btn-success", method: :patch %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <a href ="<%= root_path %>">Back to Main </a>
</div>

app/views/orders/new.html.erb
<div class="container">
  <h3>Place your Boba Order Here!</h3>
  <%= form_with model: @order do |form| %>
    <div class="card">
      <div class="card-body">
        <div class="mb-3">
          <%= form.label :first_name %><br>
          <%= form.text_field :first_name %>
          <% @order.errors.full_messages_for(:first_name).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
        <div class="mb-3">
          <%= form.label :last_name %><br>
          <%= form.text_field :last_name %>
          <% @order.errors.full_messages_for(:last_name).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
        <div class="mb-3">
          <%= form.label :drink %><br>
          <%= form.text_field :drink %>
          <% @order.errors.full_messages_for(:drink).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
        <div class="mb-3">
          <%= form.label :phone_number %><br>
          <%= form.text_field :phone_number %>
          <% @order.errors.full_messages_for(:phone_number).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
        <div class="mb-3">
          <%= form.label :special_instructions %><br>
          <%= form.text_area :special_instructions %>
          <% @order.errors.full_messages_for(:body).each do |message| %>
            div><%= message %></div>
          <% end %>
          </div>
    </div>
    <div>
      <%= form.submit "Submit", :class => "btn btn-success"%>
    </div>
    </div>

  <% end %>
</div>

app/views/orders/pickup.html.erb
<h1>Pickup!</h1>

<ul>
  <% @orders.each do |order| %>
    <li>
      <a href="<%= order_path(order) %>">
        <%= order.order_id %>
      </a>

      <%= order.status %>
    </li>
  <% end %>
</ul>

<a href ="<%= root_path %>">Back to Main </a>

app/views/orders/show.html.erb
<h1><%= @order.order_id %></h1>

<p><%= @order.status %></p>
<p><%= @order.special_instructions %></p>

<a href ="<%= root_path %>">Back to Main </a>

app/views/rooms/show.html.erb
<h1>Chat room</h1>

<!--<div id="messages">-->
  <%#= render @messages %>
<!--</div>-->

<!--<form>-->
<!--  <label>Say something:</label><br>-->
<!--  <input type="text" data-behavior="room_speaker">-->
<!--</form>-->

<div id="msg">

</div>

<%= form_for @message, remote: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>